'use client';

import { motion } from 'framer-motion';

const sections = [
  {
    title: '1. Acceptance of Terms',
    content: `By accessing or using Burnout Tracker ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree to all of the terms and conditions, you may not access or use the Platform. These terms apply to all students, counselors, and administrators using the Platform.`,
  },
  {
    title: '2. Description of Service',
    content: `Burnout Tracker is a student wellbeing intelligence platform that provides mood tracking, burnout risk assessment, personalized insights, breathing exercises, and access to AI-powered wellness assistance ("Luma"). The Platform is designed to support student mental health and is not a substitute for professional medical advice, diagnosis, or treatment.`,
  },
  {
    title: '3. User Eligibility',
    content: `The Platform is available exclusively to enrolled students, staff, and counselors at participating universities. By registering, you confirm that you are a valid member of a participating academic institution and that you will provide accurate information during registration.`,
  },
  {
    title: '4. User Accounts & Security',
    content: `You are responsible for maintaining the confidentiality of your login credentials. You agree to notify us immediately if you suspect unauthorized access to your account. Burnout Tracker reserves the right to terminate accounts that violate these terms or that show evidence of unauthorized use.`,
  },
  {
    title: '5. Data Collection & Privacy',
    content: `We collect information you provide during registration and usage including mood check-ins, burnout scores, and interaction data. This data is processed in accordance with our Privacy Policy and applicable data protection laws. Wellbeing data is treated as sensitive personal data and will never be sold to third parties.`,
  },
  {
    title: '6. AI Services (Luma)',
    content: `Our AI assistant, Luma, is provided for informational and supportive purposes only. Luma's responses are generated by an AI model and do not constitute professional counseling, therapy, or medical advice. If you are experiencing a mental health crisis, please contact your university counseling center or emergency services immediately.`,
  },
  {
    title: '7. Counselor Access',
    content: `If your burnout risk reaches a HIGH threshold, anonymized alerts may be sent to designated university counselors. You will be informed when this occurs. Counselors are bound by professional confidentiality obligations and university data policies.`,
  },
  {
    title: '8. Prohibited Conduct',
    content: `You agree not to misuse the Platform, including attempting to access other users' data, submitting false information, reverse engineering the application, or using the Platform for any unlawful purpose. Violations may result in immediate account suspension.`,
  },
  {
    title: '9. Intellectual Property',
    content: `All content, branding, design, and software within Burnout Tracker are the intellectual property of Burnout Tracker and its licensors. You may not reproduce, distribute, or create derivative works without express written permission.`,
  },
  {
    title: '10. Limitation of Liability',
    content: `To the fullest extent permitted by law, Burnout Tracker shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Platform. The Platform is provided "as is" without warranties of any kind, either express or implied.`,
  },
  {
    title: '11. Changes to Terms',
    content: `We reserve the right to update these Terms of Service at any time. Changes will be communicated via email or an in-app notification. Continued use of the Platform after changes constitutes your acceptance of the new terms.`,
  },
  {
    title: '12. Contact Us',
    content: `If you have any questions about these Terms of Service, please contact your university's designated wellbeing coordinator or reach out to our support team through the Platform's Help & Support feature.`,
  },
];

export default function TermsPage() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
    >
      {/* Header */}
      <div className="mb-12 pb-8 border-b border-white/5">
        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/20 mb-6">
          <span className="w-1.5 h-1.5 rounded-full bg-indigo-400 animate-pulse" />
          <span className="text-[10px] font-black uppercase tracking-widest text-indigo-400">Last updated: April 2025</span>
        </div>
        <h1 className="text-4xl font-black font-sora text-white tracking-tight mb-4">Terms of Service</h1>
        <p className="text-text-secondary leading-relaxed max-w-2xl">
          Please read these Terms of Service carefully before using the Burnout Tracker platform. 
          These terms govern your access to and use of our student wellbeing intelligence services.
        </p>
      </div>

      {/* Sections */}
      <div className="space-y-8">
        {sections.map((section, index) => (
          <motion.div
            key={section.title}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.04 }}
            className="p-6 rounded-2xl bg-white/[0.02] border border-white/5 hover:bg-white/[0.03] transition-colors group"
          >
            <h2 className="text-base font-bold font-sora text-white mb-3 group-hover:text-indigo-300 transition-colors">
              {section.title}
            </h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              {section.content}
            </p>
          </motion.div>
        ))}
      </div>

      {/* Agreement Footer */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.6 }}
        className="mt-12 p-6 rounded-2xl bg-indigo-500/5 border border-indigo-500/20 text-center"
      >
        <p className="text-sm text-text-secondary">
          By using Burnout Tracker, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
        </p>
        <p className="text-xs text-text-secondary/50 mt-2">
          For questions, use the Help & Support feature within the app.
        </p>
      </motion.div>
    </motion.div>
  );
}
